name: Build, publish and deploy to MonsterASP.NET
on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run:  dotnet publish EduLink.API/EduLink.API.csproj --configuration Release --output publish --runtime win-x86 --self-contained false
      - name: Inject connection string from Secrets
        shell: pwsh
        run: |
          $json = @"
          {
            "ConnectionStrings": {
              "DefaultConnection": "${{ secrets.EDULINK_CONNECTION_STRING_PRODUCTION }}"
            }
          }
          "@
          $json | Out-File -FilePath "./publish/appsettings.Production.json" -Encoding utf8
          Write-Host "✓ appsettings.Production.json created successfully"
      - name: Create Firebase config file from secret
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "./publish/firebase" -Force | Out-Null
          $firebaseConfig = @'
          ${{ secrets.FIREBASE_CONFIG_JSON }}
          '@
          $cleanJson = $firebaseConfig | ConvertFrom-Json | ConvertTo-Json -Depth 10
          Set-Content -Path "./publish/firebase/firebase-config.json" -Value $cleanJson -Encoding utf8
          Write-Host "✓ Firebase config file created successfully"
      # - name: Create Firebase config file from secret
      #   shell: pwsh
      #   run: |
      #     New-Item -ItemType Directory -Path "./publish/firebase" -Force | Out-Null
      #     Set-Content -Path "./publish/firebase/firebase-config.json" -Value '${{ secrets.FIREBASE_CONFIG_JSON }}' -Encoding utf8
      #     Write-Host "✓ Firebase config file created successfully"
      - name: Create web.config
        run: |
          $webConfig = @'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <location path="." inheritInChildApplications="false">
              <system.webServer>
                <handlers>
                  <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Either" />
                </handlers>
                <aspNetCore processPath="dotnet" 
                            arguments=".\EduLink.API.dll" 
                            stdoutLogEnabled="true" 
                            stdoutLogFile=".\logs\stdout" 
                            hostingModel="inprocess">
                  <environmentVariables>
                    <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Production" />
                  </environmentVariables>
                </aspNetCore>
              </system.webServer>
            </location>
          </configuration>
          '@
          $webConfig | Out-File -FilePath "publish/web.config" -Encoding UTF8
          Write-Host "✓ web.config created successfully"
        shell: pwsh

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: publish