name: Build, publish and deploy to MonsterASP.NET

on: 
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ github.workspace }}
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ github.workspace }}
        
      - name: Publish
        run: dotnet publish EduLink.API/EduLink.API.csproj --configuration Release --output publish --runtime win-x86 --self-contained false
        working-directory: ${{ github.workspace }}
        
      - name: Create logs directory
        run: New-Item -ItemType Directory -Force -Path "publish/logs"
        working-directory: ${{ github.workspace }}
        shell: pwsh
        
      - name: Update appsettings with secrets
        run: |
          $appsettingsPath = "publish/appsettings.Production.json"
          $appsettings = Get-Content $appsettingsPath -Raw | ConvertFrom-Json
          $appsettings.ConnectionStrings.DefaultConnection = "${{ secrets.CONNECTION_STRING }}"
          $appsettings.Google.ClientId = "${{ secrets.GOOGLE_CLIENT_ID }}"
          $appsettings.Google.ClientSecret = "${{ secrets.GOOGLE_CLIENT_SECRET }}"
          $appsettings | ConvertTo-Json -Depth 10 | Set-Content $appsettingsPath -Encoding UTF8
          Write-Host "✓ appsettings.Production.json updated successfully"
        working-directory: ${{ github.workspace }}
        shell: pwsh
        
      - name: Create web.config
        run: |
          $webConfig = @'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <location path="." inheritInChildApplications="false">
              <system.webServer>
                <handlers>
                  <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Either" />
                </handlers>
                <aspNetCore processPath="dotnet" 
                            arguments=".\EduLink.API.dll" 
                            stdoutLogEnabled="true" 
                            stdoutLogFile=".\logs\stdout" 
                            hostingModel="inprocess">
                  <environmentVariables>
                    <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Production" />
                  </environmentVariables>
                </aspNetCore>
              </system.webServer>
            </location>
          </configuration>
          '@
          $webConfig | Out-File -FilePath "publish/web.config" -Encoding UTF8
          Write-Host "✓ web.config created successfully"
        working-directory: ${{ github.workspace }}
        shell: pwsh
        
      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: publish